### ISSUE TITLE
Investigate Data Issues

### ISSUE THREAD

**Issue by qwwqwwq** [sfbrigade/datasci-housing-pipeline#12]
We need to investigate issues such as data duplication, etc.

**Comment by thfield** [comment]
For the duplicate entries you have listed in the README, I would guess there was a mistake during data entry.  The PLN_DESC states there are two houses being built on lots 48 & 49 for APN 5336048 (APN is a combination of block# and lot#)
How many other duplicate entries have you come across?  We could see about contacting the data owner and politely assisting them with making corrections
